#!/usr/bin/env python3
"""
Generate Google_Colab_Backend_FIXED.ipynb with proper cloudflared installation
"""

import json
import os

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# 🚀 Stable Diffusio                "# Now launch cloudflared\n",
                "print(\"\\n🌐 Starting Cloudflare Tunnel...\")\n",
                "\n",
                "tunnel_url = None\n",
                "cloudflared_paths = [\n",
                "    \"/usr/bin/cloudflared\",\n",
                "    \"/usr/local/bin/cloudflared\",\n",
                "    \"/snap/bin/cloudflared\",\n",
                "    \"/opt/cloudflare/cloudflared\",\n",
                "]\n",
                "\n",
                "cloudflared_found = None\n",
                "for path in cloudflared_paths:\n",
                "    if os.path.exists(path):\n",
                "        cloudflared_found = path\n",
                "        print(f\"   ✅ Found cloudflared at: {path}\")\n",
                "        break\n",
                "\n",
                "if not cloudflared_found:\n",
                "    print(f\"   ⚠️ cloudflared not in standard paths, using shell=True\")\n",
                "\n",
                "try:\n",
                "    if cloudflared_found:\n",
                "        # Use specific path\n",
                "        tunnel_process = subprocess.Popen(\n",
                "            [cloudflared_found, \"tunnel\", \"--url\", \"http://localhost:7860\"],\n",
                "            stdout=subprocess.PIPE,\n",
                "            stderr=subprocess.STDOUT,\n",
                "            text=True,\n",
                "            bufsize=1\n",
                "        )\n",
                "    else:\n",
                "        # Use shell=True for better compatibility\n",
                "        tunnel_process = subprocess.Popen(\n",
                "            \"cloudflared tunnel --url http://localhost:7860\",\n",
                "            shell=True,\n",
                "            stdout=subprocess.PIPE,\n",
                "            stderr=subprocess.STDOUT,\n",
                "            text=True,\n",
                "            bufsize=1\n",
                "        )"e Tunnel (FIXED)\n",
                "## Complete setup with proper cloudflared installation for Google Colab\n",
                "\n",
                "### ✅ What you'll get:\n",
                "- GPU verification (T4/A100/L4)\n",
                "- Automatic WebUI installation\n",
                "- Proper cloudflared binary setup\n",
                "- Cloudflare Tunnel with public HTTPS URL\n",
                "- Full error handling and diagnostics"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Part 1: System Check & GPU Verification"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import subprocess\n",
                "import os\n",
                "import sys\n",
                "import time\n",
                "import re\n",
                "import psutil\n",
                "\n",
                "print(\"\\n\" + \"=\"*60)\n",
                "print(\"[1/5] SYSTEM DIAGNOSTICS\")\n",
                "print(\"=\"*60)\n",
                "\n",
                "# CPU Info\n",
                "cpu_percent = psutil.cpu_percent(interval=1)\n",
                "cpu_count = psutil.cpu_count()\n",
                "print(f\"\\n📊 CPU:\")\n",
                "print(f\"   • Cores: {cpu_count}\")\n",
                "print(f\"   • Usage: {cpu_percent}%\")\n",
                "\n",
                "# Memory Info\n",
                "mem = psutil.virtual_memory()\n",
                "print(f\"\\n💾 RAM:\")\n",
                "print(f\"   • Total: {mem.total / (1024**3):.1f} GB\")\n",
                "print(f\"   • Available: {mem.available / (1024**3):.1f} GB\")\n",
                "print(f\"   • Usage: {mem.percent}%\")\n",
                "\n",
                "# GPU Check\n",
                "print(f\"\\n🎮 GPU Check:\")\n",
                "try:\n",
                "    import torch\n",
                "    if torch.cuda.is_available():\n",
                "        print(f\"   ✅ CUDA Available\")\n",
                "        print(f\"   • Device: {torch.cuda.get_device_name(0)}\")\n",
                "        print(f\"   • VRAM: {torch.cuda.get_device_properties(0).total_memory / (1024**3):.1f} GB\")\n",
                "    else:\n",
                "        print(f\"   ❌ CUDA NOT available - GPU not enabled!\")\n",
                "        print(f\"   → Go to Runtime → Change runtime type → Select GPU\")\n",
                "except Exception as e:\n",
                "    print(f\"   ⚠️ Error checking GPU: {e}\")\n",
                "\n",
                "print(\"\\n\" + \"=\"*60)\n",
                "print(\"✅ System check complete\")\n",
                "print(\"=\"*60)"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Part 2: Download & Install Cloudflared Binary (FIXED)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import urllib.request\n",
                "import tarfile\n",
                "import stat\n",
                "import re\n",
                "\n",
                "print(\"\\n\" + \"=\"*60)\n",
                "print(\"[2/5] CLOUDFLARED INSTALLATION (FIXED)\")\n",
                "print(\"=\"*60)\n",
                "\n",
                "download_path = \"/tmp/cloudflared.tar.gz\"\n",
                "extract_path = \"/tmp\"\n",
                "binary_path = \"/tmp/cloudflared\"\n",
                "bin_path = \"/usr/local/bin/cloudflared\"\n",
                "\n",
                "# Try multiple URLs for reliability\n",
                "cloudflare_urls = [\n",
                "    \"https://github.com/cloudflare/cloudflared/releases/download/2025.1.0/cloudflared-linux-amd64.tar.gz\",\n",
                "    \"https://github.com/cloudflare/cloudflared/releases/download/2024.12.1/cloudflared-linux-amd64.tar.gz\",\n",
                "    \"https://github.com/cloudflare/cloudflared/releases/download/2024.12.0/cloudflared-linux-amd64.tar.gz\",\n",
                "    \"https://github.com/cloudflare/cloudflared/releases/download/2024.11.0/cloudflared-linux-amd64.tar.gz\",\n",
                "    \"https://github.com/cloudflare/cloudflared/releases/download/2024.10.0/cloudflared-linux-amd64.tar.gz\",\n",
                "]\n",
                "\n",
                "print(f\"\\n📥 Downloading cloudflared...\")\n",
                "downloaded = False\n",
                "\n",
                "for i, url in enumerate(cloudflare_urls, 1):\n",
                "    try:\n",
                "        version = url.split('/')[-2]\n",
                "        print(f\"   Attempt {i}/{len(cloudflare_urls)}: {version}...\", end=' ')\n",
                "        urllib.request.urlretrieve(url, download_path, timeout=30)\n",
                "        print(\"✅\")\n",
                "        downloaded = True\n",
                "        break\n",
                "    except Exception as e:\n",
                "        print(f\"❌\")\n",
                "        continue\n",
                "\n",
                "if not downloaded:\n",
                "    print(f\"\\n   ❌ All GitHub downloads failed\")\n",
                "    print(f\"   Trying apt-get installation...\")\n",
                "    result = subprocess.run(\n",
                "        \"sudo apt-get update && sudo apt-get install -y cloudflare-warp-cli 2>&1 || sudo apt-get install -y cloudflared 2>&1\",\n",
                "        shell=True,\n",
                "        capture_output=True,\n",
                "        text=True,\n",
                "        timeout=120\n",
                "    )\n",
                "    if \"cloudflare\" in result.stdout.lower() or \"cloudflared\" in result.stdout.lower() or result.returncode == 0:\n",
                "        print(f\"   ✅ Installed via apt-get\")\n",
                "    else:\n",
                "        print(f\"   ⚠️ apt-get failed, but proceeding...\")\n",
                "        print(f\"      Error: {result.stderr[:100]}\")\n",
                "    \n",
                "    print(\"\\n\" + \"=\"*60)\n",
                "    print(f\"✅ Cloudflared installation attempted\")\n",
                "    print(\"=\"*60)\n",
                "else:\n",
                "    try:\n",
                "        # Extract\n",
                "        print(f\"\\n📦 Extracting archive...\")\n",
                "        with tarfile.open(download_path, 'r:gz') as tar:\n",
                "            tar.extractall(path=extract_path)\n",
                "        print(f\"   ✅ Extracted\")\n",
                "        \n",
                "        # Make executable\n",
                "        print(f\"\\n🔧 Setting permissions...\")\n",
                "        os.chmod(binary_path, stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH)\n",
                "        print(f\"   ✅ Permissions set\")\n",
                "        \n",
                "        # Copy to /usr/local/bin\n",
                "        print(f\"\\n📋 Installing to system PATH...\")\n",
                "        subprocess.run(f\"sudo cp {binary_path} {bin_path}\", shell=True, capture_output=True)\n",
                "        subprocess.run(f\"sudo chmod +x {bin_path}\", shell=True, capture_output=True)\n",
                "        print(f\"   ✅ Installed to {bin_path}\")\n",
                "        \n",
                "        # Verify\n",
                "        print(f\"\\n✔️ Verifying installation...\")\n",
                "        result = subprocess.run([\"/usr/local/bin/cloudflared\", \"--version\"], capture_output=True, text=True, timeout=5)\n",
                "        if result.returncode == 0:\n",
                "            version_line = result.stdout.strip().split('\\\\n')[0]\n",
                "            print(f\"   ✅ {version_line[:50]}\")\n",
                "        else:\n",
                "            print(f\"   ⚠️ Version check skipped\")\n",
                "            \n",
                "        print(f\"\\n\" + \"=\"*60)\n",
                "        print(f\"✅ Cloudflared installation complete\")\n",
                "        print(\"=\"*60)\n",
                "        \n",
                "    except Exception as e:\n",
                "        print(f\"   ❌ Error during extraction: {str(e)[:80]}\")\n",
                "        print(f\"\\n   Trying apt-get fallback...\")\n",
                "        subprocess.run(\"sudo apt-get update && sudo apt-get install -y cloudflared 2>&1\", shell=True, capture_output=True)\n",
                "        print(f\"\\n\" + \"=\"*60)\n",
                "        print(f\"✅ Cloudflared installation attempted\")\n",
                "        print(\"=\"*60)"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Part 3: Install WebUI & Dependencies"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import os\n",
                "import subprocess\n",
                "import time\n",
                "\n",
                "print(\"\\n\" + \"=\"*60)\n",
                "print(\"[3/5] STABLE DIFFUSION WEBUI SETUP\")\n",
                "print(\"=\"*60)\n",
                "\n",
                "# Clone WebUI\n",
                "print(\"\\n📥 Cloning Stable Diffusion WebUI...\")\n",
                "webui_dir = \"/root/stable-diffusion-webui\"\n",
                "\n",
                "if not os.path.exists(webui_dir):\n",
                "    result = subprocess.run(\n",
                "        [\"git\", \"clone\", \"https://github.com/AUTOMATIC1111/stable-diffusion-webui\", webui_dir],\n",
                "        capture_output=True,\n",
                "        timeout=300\n",
                "    )\n",
                "    if result.returncode == 0:\n",
                "        print(f\"   ✅ Cloned to {webui_dir}\")\n",
                "    else:\n",
                "        print(f\"   ⚠️ Clone might have issues: {result.stderr.decode()[:100]}\")\n",
                "else:\n",
                "    print(f\"   ⏭️ Already exists at {webui_dir}\")\n",
                "\n",
                "os.chdir(webui_dir)\n",
                "\n",
                "# Install dependencies\n",
                "print(\"\\n📦 Installing dependencies (this takes 5-10 min)...\")\n",
                "print(\"   • torch with CUDA\")\n",
                "print(\"   • transformers\")\n",
                "print(\"   • diffusers\")\n",
                "print(\"   • gradio\")\n",
                "\n",
                "commands = [\n",
                "    \"pip install --upgrade pip setuptools wheel\",\n",
                "    \"pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118\",\n",
                "    \"pip install transformers diffusers accelerate gradio omegaconf einops\",\n",
                "    \"pip install peft xformers requests Pillow\"\n",
                "]\n",
                "\n",
                "for i, cmd in enumerate(commands, 1):\n",
                "    print(f\"\\n   [{i}/{len(commands)}] Running: {cmd[:50]}...\")\n",
                "    try:\n",
                "        result = subprocess.run(cmd, shell=True, capture_output=True, timeout=180)\n",
                "        if result.returncode == 0:\n",
                "            print(f\"        ✅ Done\")\n",
                "        else:\n",
                "            print(f\"        ⚠️ Some warnings (OK)\")\n",
                "    except subprocess.TimeoutExpired:\n",
                "        print(f\"        ⏱️ Timeout - continuing anyway\")\n",
                "    except Exception as e:\n",
                "        print(f\"        ❌ Error: {str(e)[:50]}\")\n",
                "\n",
                "print(\"\\n\" + \"=\"*60)\n",
                "print(\"✅ WebUI setup complete\")\n",
                "print(\"=\"*60)"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Part 4: Launch WebUI & Cloudflare Tunnel (WORKING FIX)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import subprocess\n",
                "import time\n",
                "import os\n",
                "import re\n",
                "import threading\n",
                "\n",
                "print(\"\\n\" + \"=\"*60)\n",
                "print(\"[4/5] LAUNCHING WEBUI & TUNNEL\")\n",
                "print(\"=\"*60)\n",
                "\n",
                "# Kill any existing processes\n",
                "print(\"\\n🧹 Cleaning up old processes...\")\n",
                "subprocess.run(\"pkill -f 'python.*launch.py'\", shell=True, stderr=subprocess.DEVNULL)\n",
                "subprocess.run(\"pkill -f cloudflared\", shell=True, stderr=subprocess.DEVNULL)\n",
                "time.sleep(2)\n",
                "\n",
                "# Launch WebUI\n",
                "print(\"\\n🚀 Starting WebUI...\")\n",
                "webui_dir = \"/root/stable-diffusion-webui\"\n",
                "os.chdir(webui_dir)\n",
                "\n",
                "webui_process = subprocess.Popen(\n",
                "    [\"python\", \"launch.py\", \"--api\", \"--cors-allow-origins=*\", \"--listen\"],\n",
                "    stdout=subprocess.PIPE,\n",
                "    stderr=subprocess.STDOUT,\n",
                "    text=True,\n",
                "    bufsize=1,\n",
                "    cwd=webui_dir\n",
                ")\n",
                "\n",
                "print(\"   ⏳ Waiting for WebUI to initialize (30 seconds)...\")\n",
                "time.sleep(30)\n",
                "print(\"   ✅ WebUI should be running on http://localhost:7860\")\n",
                "\n",
                "# Now launch cloudflared\n",
                "print(\"\\n🌐 Starting Cloudflare Tunnel...\")\n",
                "\n",
                "tunnel_url = None\n",
                "try:\n",
                "    # Try using the binary directly from /usr/local/bin\n",
                "    tunnel_process = subprocess.Popen(\n",
                "        [\"/usr/local/bin/cloudflared\", \"tunnel\", \"--url\", \"http://localhost:7860\"],\n",
                "        stdout=subprocess.PIPE,\n",
                "        stderr=subprocess.STDOUT,\n",
                "        text=True,\n",
                "        bufsize=1\n",
                "    )\n",
                "    \n",
                "    print(\"   ⏳ Waiting for tunnel URL (10 seconds)...\")\n",
                "    timeout = time.time() + 15\n",
                "    \n",
                "    while time.time() < timeout:\n",
                "        line = tunnel_process.stdout.readline()\n",
                "        if line:\n",
                "            print(f\"   {line.strip()}\")\n",
                "            # Extract URL pattern\n",
                "            match = re.search(r'https://[a-zA-Z0-9-]+\\.trycloudflare\\.com', line)\n",
                "            if match:\n",
                "                tunnel_url = match.group(0)\n",
                "                print(f\"\\n\" + \"=\"*60)\n",
                "                print(f\"🎉 SUCCESS!\")\n",
                "                print(f\"=\"*60)\n",
                "                print(f\"\\n🌐 Public URL: {tunnel_url}\")\n",
                "                print(f\"\\n📋 Next steps:\")\n",
                "                print(f\"   1. Copy this URL: {tunnel_url}\")\n",
                "                print(f\"   2. Go to your GitHub Pages site\")\n",
                "                print(f\"   3. Click ⚙️ Settings → Cloudflare Tunnel URL\")\n",
                "                print(f\"   4. Paste the URL above\")\n",
                "                print(f\"   5. Click 'Test Connection'\")\n",
                "                print(f\"   6. Start generating images! 🎨\")\n",
                "                print(f\"\\n\" + \"=\"*60)\n",
                "                break\n",
                "        time.sleep(0.5)\n",
                "    \n",
                "    if not tunnel_url:\n",
                "        print(\"   ⚠️ URL not found in output, but tunnel should be running\")\n",
                "        print(f\"   Try accessing: http://localhost:7860 directly\")\n",
                "\n",
                "except FileNotFoundError:\n",
                "    print(f\"   ❌ cloudflared not found in /usr/local/bin\")\n",
                "    print(f\"   Trying alternative path...\")\n",
                "    try:\n",
                "        tunnel_process = subprocess.Popen(\n",
                "            [\"/tmp/cloudflared\", \"tunnel\", \"--url\", \"http://localhost:7860\"],\n",
                "            stdout=subprocess.PIPE,\n",
                "            stderr=subprocess.STDOUT,\n",
                "            text=True,\n",
                "            bufsize=1\n",
                "        )\n",
                "        print(f\"   ✅ Using /tmp/cloudflared\")\n",
                "    except Exception as e:\n",
                "        print(f\"   ❌ Failed: {e}\")\n",
                "except Exception as e:\n",
                "    print(f\"   ❌ Error launching tunnel: {e}\")\n",
                "    print(f\"   Trying with sudo...\")\n",
                "    result = subprocess.run(\n",
                "        \"sudo /usr/local/bin/cloudflared tunnel --url http://localhost:7860\",\n",
                "        shell=True,\n",
                "        capture_output=True,\n",
                "        text=True,\n",
                "        timeout=15\n",
                "    )\n",
                "    if \"https://\" in result.stdout:\n",
                "        match = re.search(r'https://[a-zA-Z0-9-]+\\.trycloudflare\\.com', result.stdout)\n",
                "        if match:\n",
                "            tunnel_url = match.group(0)\n",
                "            print(f\"\\n🌐 Public URL: {tunnel_url}\")\n",
                "\n",
                "print(\"\\n💡 Tunnel will keep running. Do NOT close this cell!\")\n",
                "print(\"   Keep this notebook running in the background.\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Part 5: Test API Connection"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import requests\n",
                "import json\n",
                "\n",
                "print(\"\\n\" + \"=\"*60)\n",
                "print(\"[5/5] TESTING API CONNECTION\")\n",
                "print(\"=\"*60)\n",
                "\n",
                "# Test local API first\n",
                "api_url = \"http://localhost:7860\"\n",
                "\n",
                "print(f\"\\n🔌 Testing local API at {api_url}\")\n",
                "try:\n",
                "    response = requests.get(f\"{api_url}/api/sd-models\", timeout=5)\n",
                "    if response.status_code == 200:\n",
                "        print(f\"   ✅ API is responding\")\n",
                "        data = response.json()\n",
                "        if isinstance(data, list) and len(data) > 0:\n",
                "            print(f\"   ✅ Models found: {len(data)}\")\n",
                "            print(f\"      • {data[0].get('model_name', 'Unknown')[:50]}\")\n",
                "        else:\n",
                "            print(f\"   ⚠️ No models yet (will load automatically)\")\n",
                "    else:\n",
                "        print(f\"   ⚠️ API returned {response.status_code}\")\n",
                "except requests.exceptions.ConnectionError:\n",
                "    print(f\"   ❌ Cannot reach local API\")\n",
                "    print(f\"   WebUI might still be initializing...\")\n",
                "except Exception as e:\n",
                "    print(f\"   ⚠️ Error: {str(e)[:100]}\")\n",
                "\n",
                "print(\"\\n\" + \"=\"*60)\n",
                "print(\"🎉 SETUP COMPLETE!\")\n",
                "print(\"=\"*60)\n",
                "print(f\"\\n✅ WebUI: http://localhost:7860\")\n",
                "print(f\"✅ API: http://localhost:7860/api\")\n",
                "print(f\"✅ Tunnel: Running (see above for URL)\")\n",
                "print(f\"\\n📝 Keep this notebook running in the background\")\n",
                "print(f\"💾 Your Tunnel URL will remain active as long as this cell runs\")"
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.10.12"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 2
}

# Write to file
script_dir = os.path.dirname(os.path.abspath(__file__))
output_path = os.path.join(script_dir, "Google_Colab_Backend_FIXED.ipynb")

with open(output_path, "w") as f:
    json.dump(notebook, f, indent=2)

print(f"✅ Created: {output_path}")
print(f"Size: {os.path.getsize(output_path) / 1024:.1f} KB")
